/**
 * Typed registry of every internal API endpoint.
 *
 * Call sites import from here instead of hand-writing path strings. This is the
 * contract layer that prevents the class of bug where inconsistent paths
 * (`/kb/generate` vs `/api/admin/users`) silently 404. All paths are absolute
 * and include the `/api` prefix.
 */
export const ROUTES = {
  admin: {
    users: () => "/api/admin/users",
    usersSuspend: () => "/api/admin/users/suspend",
    usersLoginLink: () => "/api/admin/users/login-link",
    usersResetPassword: () => "/api/admin/users/reset-password",
    client: (id: string) => `/api/admin/clients/${id}`,
    impersonate: () => "/api/admin/impersonate",
    prompts: () => "/api/admin/prompts",
    placements: () => "/api/admin/placements",
    leads: () => "/api/admin/leads",
    leadEvents: () => "/api/admin/leads/events",
    expenses: () => "/api/admin/expenses",
    featureVideos: () => "/api/admin/feature-videos",
    guides: () => "/api/admin/guides",
    library: () => "/api/admin/library",
    libraryEntry: (id: string) => `/api/admin/library/${id}`,
    libraryAction: (id: string) => `/api/admin/library/${id}/action`,
  },
  notebook: {
    pages: () => "/api/notebook/pages",
    pagesReorder: () => "/api/notebook/pages/reorder",
    revisions: () => "/api/notebook/revisions",
    images: () => "/api/notebook/images",
  },
  kb: {
    generate: () => "/api/kb/generate",
    entry: (id: string) => `/api/kb/entries/${id}`,
  },
  vault: {
    items: () => "/api/vault/items",
    readiness: () => "/api/vault/readiness",
    recap: () => "/api/vault/recap",
    refreshDossier: () => "/api/vault/refresh-dossier",
    expand: () => "/api/vault/expand",
    unindexed: () => "/api/vault/unindexed",
    text: () => "/api/vault/text",
    url: () => "/api/vault/url",
    linkedin: () => "/api/vault/linkedin",
    crawlSite: () => "/api/vault/crawl-site",
    crawlSiteAdvance: () => "/api/vault/crawl-site/advance",
    upload: () => "/api/vault/upload",
    delete: () => "/api/vault/delete",
    ask: () => "/api/vault/ask",
    verify: () => "/api/vault/verify",
    feedback: () => "/api/vault/feedback",
    promoteKb: () => "/api/vault/promote-kb",
    teach: () => "/api/vault/teach",
    gaps: () => "/api/vault/gaps",
    item: (id: string) => `/api/vault/${id}`,
    itemVersions: (id: string) => `/api/vault/${id}/versions`,
    reprocess: (id: string) => `/api/vault/${id}/reprocess`,
  },
  sops: () => "/api/sops",
  sopRestore: () => "/api/sops/restore",
  sopFork: () => "/api/sops/fork",
  sopRun: () => "/api/sops/run",
  sopReorder: () => "/api/sops/reorder",
  sopSuggest: () => "/api/sops/suggest",
  sopGenerate: () => "/api/sops/generate",
  sopSuggestions: () => "/api/sops/suggestions",
  sopSuggestionsProduce: () => "/api/sops/suggestions/produce",
  sopBulk: () => "/api/sops/bulk",
  sopCategories: () => "/api/sops/categories",
  crm: {
    contacts: () => "/api/crm/contacts",
    notes: () => "/api/crm/notes",
    events: () => "/api/crm/events",
  },
  content: {
    pieces: () => "/api/content/pieces",
    piecesPage: (clientId: string, offset: number, limit = 50) =>
      `/api/content/pieces?client_id=${clientId}&offset=${offset}&limit=${limit}`,
    projects: () => "/api/content/projects",
    projectsForClient: (clientId: string) => `/api/content/projects?client_id=${clientId}`,
    projectsPage: (clientId: string, offset: number, limit = 100) =>
      `/api/content/projects?client_id=${clientId}&offset=${offset}&limit=${limit}`,
    project: (clientId: string, projectId: string) =>
      `/api/content/projects?client_id=${clientId}&id=${projectId}`,
    projectArtifacts: (clientId: string, projectId: string, offset: number, limit = 100) =>
      `/api/content/projects?client_id=${clientId}&id=${projectId}&artifact_offset=${offset}&artifact_limit=${limit}`,
    projectEvidence: (clientId: string, projectId: string) =>
      `/api/content/projects/evidence?client_id=${clientId}&project_id=${projectId}`,
    validate: () => "/api/content/validate",
    generate: () => "/api/content/generate",
    styleAnalysis: () => "/api/content/style-analysis",
    styleAnalysisForClient: (clientId: string) => `/api/content/style-analysis?client_id=${clientId}`,
    goldens: () => "/api/content/goldens",
    goldensForClient: (clientId: string) => `/api/content/goldens?client_id=${clientId}`,
    voiceEvaluations: () => "/api/content/voice-evaluations",
    voiceEvaluationsForClient: (clientId: string) => `/api/content/voice-evaluations?client_id=${clientId}`,
    pilot: () => "/api/content/pilot",
    pilotForClient: (clientId: string) => `/api/content/pilot?client_id=${clientId}`,
    competitorIntelligence: () => "/api/content/competitors/intelligence",
    competitorIntelligenceForClient: (clientId: string) =>
      `/api/content/competitors/intelligence?client_id=${clientId}`,
    topics: () => "/api/content/topics",
    topicsForClient: (clientId: string) => `/api/content/topics?client_id=${clientId}`,
    topicsGenerate: () => "/api/content/topics/generate",
  },
  brain: {
    signals: () => "/api/brain/signals",
    learningInbox: () => "/api/brain/learning-inbox",
    learningInboxForClient: (clientId: string) =>
      `/api/brain/learning-inbox?client_id=${clientId}`,
    onboard: () => "/api/brain/onboard",
    memory: () => "/api/brain/memory",
    memoryForClient: (clientId: string) => `/api/brain/memory?client_id=${clientId}`,
    memoryDistill: () => "/api/brain/memory/distill",
    opportunities: () => "/api/brain/opportunities",
    opportunitiesForClient: (clientId: string) =>
      `/api/brain/opportunities?clientId=${clientId}`,
    opportunity: (id: string) => `/api/brain/opportunities/${id}`,
  },
  tasks: () => "/api/tasks",
  taskEvents: () => "/api/tasks/events",
  taskReview: () => "/api/tasks/review",
  taskCategories: () => "/api/tasks/categories",
  taskRecurrences: () => "/api/tasks/recurrences",
  tools: {
    meta: () => "/api/tools/meta",
    gbp: () => "/api/tools/gbp",
    keywordBrief: () => "/api/tools/keyword-brief",
    contentAuditor: () => "/api/tools/content-auditor",
    fetchUrl: () => "/api/tools/fetch-url",
    calendar: () => "/api/tools/calendar",
    repurposer: () => "/api/tools/repurposer",
    replyAssistant: () => "/api/tools/reply-assistant",
    hooks: () => "/api/tools/hooks",
    newsletter: () => "/api/tools/newsletter",
    adCopy: () => "/api/tools/ad-copy",
    carousel: () => "/api/tools/carousel",
    hashtags: () => "/api/tools/hashtags",
    spintax: () => "/api/tools/spintax",
    followUp: () => "/api/tools/follow-up",
    personalisation: () => "/api/tools/personalisation",
    replyClassifier: () => "/api/tools/reply-classifier",
  },
  goldenQuestions: () => "/api/golden-questions",
  notifications: () => "/api/notifications",
  access: () => "/api/access",
  accessReveal: () => "/api/access/reveal",
  accessReveals: () => "/api/access/reveals",
  timeEntries: () => "/api/time-entries",
  team: (id: string) => `/api/team/${id}`,
  profile: () => "/api/profile",
  profileNotifications: () => "/api/profile/notifications",
  messages: {
    list: (clientId: string) => `/api/messages?clientId=${clientId}`,
    send: () => "/api/messages/send",
  },
  myJob: {
    contract: (userId?: string) => `/api/my-job/contract${userId ? `?userId=${userId}` : ""}`,
    contractDocument: (userId?: string) => `/api/my-job/contract/document${userId ? `?userId=${userId}` : ""}`,
    days: () => "/api/my-job/days",
    leave: () => "/api/my-job/leave",
    issues: () => "/api/my-job/issues",
    selfReport: () => "/api/my-job/self-report",
  },
  dailyLog: {
    upsert: () => "/api/daily-log/upsert",
    notes: () => "/api/daily-log/notes",
    note: (id: string) => `/api/daily-log/notes?id=${id}`,
    feedback: () => "/api/daily-log/feedback",
  },
  companyDna: {
    base: () => "/api/company-dna",
    scrape: () => "/api/company-dna/scrape",
  },
} as const;
