import { redirect } from "next/navigation";
import { getCurrentUserAndClient } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { DocumentShell } from "@/components/my-job/DocumentShell";
import { fmtMoney } from "@/lib/my-job/pay";
import { formatDate } from "@/lib/utils";
import { differenceInCalendarMonths } from "date-fns";

export const dynamic = "force-dynamic";
export const metadata = { title: "Certificate of Employment — RapidTal" };

/**
 * Certificate of Employment / proof of income — auto-generated from contract
 * and tenure data. Needed for loans, credit cards, visas, renting.
 * ?income=1 includes the compensation line (leave it off for documents where
 * income shouldn't be disclosed).
 */
export default async function CertificatePage({ searchParams }: { searchParams: { income?: string } }) {
  const ctx = await getCurrentUserAndClient();
  if (!ctx) redirect("/login");
  const { user, client } = ctx;
  if (!["va", "client_admin"].includes(user.role)) redirect("/dashboard");

  const includeIncome = searchParams.income === "1";

  const admin = createAdminClient();
  const { data: contractRow } = await admin
    .from("va_job_contracts")
    .select("rate, currency, pay_period, start_date, weekly_hours")
    .eq("user_id", user.id)
    .maybeSingle();
  const c = contractRow as { rate: number | null; currency: string; pay_period: string; start_date: string | null; weekly_hours: number | null } | null;

  const name = user.full_name ?? user.email;
  const start = c?.start_date ? new Date(c.start_date + "T00:00:00") : null;
  const months = start ? differenceInCalendarMonths(new Date(), start) : null;
  const tenure = months == null ? null : months >= 12 ? `${Math.floor(months / 12)} year${Math.floor(months / 12) !== 1 ? "s" : ""}${months % 12 ? ` and ${months % 12} month${months % 12 !== 1 ? "s" : ""}` : ""}` : `${months} month${months !== 1 ? "s" : ""}`;
  const startLabel = start ? start.toLocaleDateString("en", { day: "numeric", month: "long", year: "numeric" }) : null;
  const today = formatDate(new Date(), { day: "numeric", month: "long", year: "numeric" });

  return (
    <DocumentShell>
      <div className="text-center mb-12">
        <p className="text-xs uppercase tracking-[0.3em] text-zinc-400 mb-2">RapidTal</p>
        <h1 className="text-2xl font-bold tracking-tight">Certificate of Engagement{includeIncome ? " & Income" : ""}</h1>
      </div>

      <p className="text-sm mb-6">{today}</p>
      <p className="text-sm font-semibold mb-6">TO WHOM IT MAY CONCERN:</p>

      <div className="text-sm leading-relaxed space-y-4 mb-10">
        <p>
          This is to certify that <span className="font-semibold">{name}</span> is engaged as a remote
          Virtual Assistant through RapidTal{client?.name ? <>, providing services to <span className="font-semibold">{client.name}</span></> : null}
          {startLabel ? <>, commencing on <span className="font-semibold">{startLabel}</span></> : null}
          {tenure ? <> ({tenure} of continuous engagement to date)</> : null}.
        </p>
        {c?.weekly_hours ? (
          <p>The engagement is for approximately <span className="font-semibold">{c.weekly_hours} hours per week</span> on an ongoing basis.</p>
        ) : null}
        {includeIncome && c?.rate != null ? (
          <p>
            Current compensation under this engagement is <span className="font-semibold">{fmtMoney(c.rate, c.currency)} per {c.pay_period === "hourly" ? "hour" : c.pay_period === "daily" ? "day" : c.pay_period.replace("ly", "")}</span>.
          </p>
        ) : null}
        <p>
          This certificate is issued upon the request of {name} for whatever legitimate purpose it may serve
          (e.g. loan, credit, visa or tenancy applications).
        </p>
      </div>

      <div className="mt-16 text-sm">
        <div className="w-56 border-t border-zinc-400 pt-2">
          <p className="font-semibold">RapidTal</p>
          <p className="text-zinc-500 text-xs">Talent Operations</p>
        </div>
      </div>

      <p className="text-[10px] text-zinc-400 mt-12">
        Generated by RapidTal Portal from contract and tenure records on {today}. Verification: contact RapidTal with reference {user.id.slice(0, 8).toUpperCase()}.
      </p>
    </DocumentShell>
  );
}
