"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";
import { api } from "@/lib/api-client";
import { ROUTES } from "@/lib/api/routes";
import { Button } from "@/components/ui/button";
import { Markdown } from "./Markdown";
import { Telescope, Loader2, RefreshCw, Sparkles, Info } from "lucide-react";

interface Analysis {
  content: string;
  model: string | null;
  source_url: string | null;
  updated_at: string;
}

export function VaultExpanded({ clientId, canWrite }: { clientId: string; canWrite: boolean }) {
  const [analysis, setAnalysis] = useState<Analysis | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    api.get<{ analysis: Analysis | null }>(`${ROUTES.vault.expand()}?clientId=${clientId}`, { showErrorToast: false })
      .then((d) => { if (!cancelled) setAnalysis(d.analysis); })
      .catch(() => { if (!cancelled) setAnalysis(null); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [clientId]);

  async function generate() {
    setGenerating(true);
    try {
      const { analysis: a } = await api.post<{ analysis: Analysis }>(
        ROUTES.vault.expand(), { clientId }, { showErrorToast: false },
      );
      setAnalysis(a);
      toast.success("Deep analysis ready.");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Couldn't generate the analysis.");
    } finally {
      setGenerating(false);
    }
  }

  if (loading) {
    return <div className="flex items-center justify-center py-20"><Loader2 className="w-5 h-5 animate-spin text-zinc-500" /></div>;
  }

  const generatingState = (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <Loader2 className="w-6 h-6 animate-spin text-violet-400 mb-3" />
      <p className="text-sm text-zinc-300 font-medium">Analyzing the whole corpus…</p>
      <p className="text-xs text-zinc-500 mt-1">A frontier model is reading the dossier, catalog, and every page. ~30 seconds.</p>
    </div>
  );

  if (!analysis) {
    return (
      <div className="max-w-3xl">
        {generating ? generatingState : (
          <div className="rounded-xl border border-dashed border-zinc-800 bg-zinc-900/50 p-12 text-center">
            <div className="w-12 h-12 rounded-2xl bg-violet-500/15 flex items-center justify-center mx-auto mb-4">
              <Telescope className="w-6 h-6 text-violet-400" />
            </div>
            <p className="text-zinc-200 font-semibold text-lg">Expanded View</p>
            <p className="text-zinc-500 text-sm mt-1 max-w-md mx-auto">
              A deeper, strategic read of this company — industry context, positioning, brand voice,
              audience, competitive landscape, and opportunities. Generated by a frontier model over
              everything we&apos;ve crawled.
            </p>
            {canWrite ? (
              <Button onClick={generate} className="gap-1.5 mt-5">
                <Sparkles className="w-4 h-4" /> Generate deep analysis
              </Button>
            ) : (
              <p className="text-xs text-zinc-600 mt-5">No analysis yet — ask an admin to generate it.</p>
            )}
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="max-w-3xl">
      <div className="flex items-center gap-2 mb-4">
        <Telescope className="w-4 h-4 text-violet-400" />
        <h2 className="text-sm font-semibold text-violet-300 uppercase tracking-wide">Expanded View</h2>
        <span className="text-xs text-zinc-600">
          {analysis.model} · {new Date(analysis.updated_at).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" })}
        </span>
        {canWrite && (
          <Button size="sm" variant="outline" onClick={generate} disabled={generating} className="ml-auto gap-1.5 border-zinc-700 h-8 text-xs">
            {generating ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <RefreshCw className="w-3.5 h-3.5" />}
            Regenerate
          </Button>
        )}
      </div>

      <div className="flex items-start gap-2 mb-5 rounded-lg border border-zinc-800 bg-zinc-900/60 px-3 py-2">
        <Info className="w-3.5 h-3.5 text-zinc-500 shrink-0 mt-0.5" />
        <p className="text-xs text-zinc-500">
          Strategic interpretation, not verified fact — industry and competitive points are informed analysis.
          This is for your team to read; Ask the Vault still answers only from the grounded dossier.
        </p>
      </div>

      {generating ? generatingState : <div className="surface-card rounded-xl p-5"><Markdown content={analysis.content} /></div>}
    </div>
  );
}
