import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentUserAndClient } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { ClientDetail } from "@/components/admin/ClientDetail";
import type { UserRole } from "@/types/database";
import { CheckCircle2, Circle, ArrowRight, ClipboardCheck } from "lucide-react";

export const dynamic = "force-dynamic";

interface Props {
  params: { id: string };
}

export default async function AdminClientDetailPage({ params }: Props) {
  const ctx = await getCurrentUserAndClient();
  if (!ctx) redirect("/login");
  if (ctx.user.role !== "super_admin") redirect("/dashboard");

  const admin = createAdminClient();

  const [{ data: client }, { data: users }, { data: unassignedVas }] =
    await Promise.all([
      admin
        .from("clients")
        .select("id, name, slug, created_at")
        .eq("id", params.id)
        .single(),
      admin
        .from("users")
        .select("id, email, full_name, role, created_at")
        .eq("client_id", params.id)
        .order("created_at", { ascending: true }),
      admin
        .from("users")
        .select("id, email, full_name")
        .is("client_id", null)
        .eq("role", "va")
        .order("email", { ascending: true }),
    ]);

  if (!client) redirect("/admin/clients");

  // ── Onboarding checklist — is this client actually set up? ──────────
  const [{ count: vaultCount }, { data: dossierRow }, { data: dna }, { count: gqCount }] = await Promise.all([
    admin.from("vault_items").select("id", { count: "exact", head: true }).eq("client_id", params.id),
    admin.from("vault_items").select("id").eq("client_id", params.id).contains("tags", ["dossier"]).limit(1).maybeSingle(),
    admin.from("company_dna").select("company_name, services").eq("client_id", params.id).maybeSingle(),
    admin.from("golden_questions").select("id", { count: "exact", head: true }).eq("client_id", params.id),
  ]);

  const userRows = (users ?? []) as { role: string }[];
  const dnaRow = dna as { company_name: string | null; services: string | null } | null;
  const checklist = [
    { done: userRows.some((u) => u.role === "client_admin"), label: "Client admin added", href: "/admin/users", hint: "Create their login in All Users" },
    { done: userRows.some((u) => u.role === "va"), label: "VA assigned", href: null, hint: "Assign one below" },
    { done: (vaultCount ?? 0) > 0, label: "Vault fed", href: `/admin/vault?client=${params.id}`, hint: "Crawl their website or add documents" },
    { done: !!dossierRow, label: "Company Dossier created", href: `/admin/vault?client=${params.id}`, hint: "Generated by a site crawl or on the Recap tab" },
    { done: !!(dnaRow?.company_name || dnaRow?.services), label: "Company DNA filled", href: `/admin/vault?client=${params.id}`, hint: "A site crawl fills this automatically" },
    { done: (gqCount ?? 0) > 0, label: "Golden questions saved", href: `/admin/ask?client=${params.id}`, hint: "Save the questions their Brain must answer" },
  ];
  const doneCount = checklist.filter((c) => c.done).length;

  return (
    <>
      <div className="surface-card rounded-xl p-4 mb-6">
        <div className="flex items-center gap-2 mb-1">
          <ClipboardCheck className={doneCount === checklist.length ? "w-4 h-4 text-green-400" : "w-4 h-4 text-amber-400"} />
          <p className="text-sm font-semibold text-zinc-100">Onboarding</p>
          <span className="text-xs text-zinc-500">{doneCount}/{checklist.length} complete</span>
        </div>
        {doneCount === checklist.length ? (
          <p className="text-xs text-green-500/80 mt-1">This client is fully set up.</p>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-1.5 mt-2">
            {checklist.map((c) => (
              <div key={c.label} className="flex items-center gap-2 text-sm">
                {c.done
                  ? <CheckCircle2 className="w-4 h-4 text-green-500 shrink-0" />
                  : <Circle className="w-4 h-4 text-zinc-600 shrink-0" />}
                <span className={c.done ? "text-zinc-400" : "text-zinc-200"}>{c.label}</span>
                {!c.done && c.href && (
                  <Link href={c.href} title={c.hint}
                    className="inline-flex items-center gap-0.5 text-xs text-blue-400 hover:text-blue-300 ml-auto">
                    {c.hint} <ArrowRight className="w-3 h-3" />
                  </Link>
                )}
                {!c.done && !c.href && <span className="text-xs text-zinc-500 ml-auto">{c.hint}</span>}
              </div>
            ))}
          </div>
        )}
      </div>

      <ClientDetail
      client={client as { id: string; name: string; slug: string; created_at: string }}
      users={
        (users ?? []) as {
          id: string;
          email: string;
          full_name: string | null;
          role: UserRole;
          created_at: string;
        }[]
      }
      unassignedVas={
        (unassignedVas ?? []) as {
          id: string;
          email: string;
          full_name: string | null;
        }[]
      }
    />
    </>
  );
}
